### ISSUE TITLE
IP address is not getting collected

### ISSUE THREAD

**Issue by epopov** [segmentio/Analytics.Xamarin#18]
How can I turn on collecting IP address and deviceID on iOS and Android app using Xamarin SDK ? I don’t see IP address in my BigQuery warehouse and in raw event data:
"anonymousId": "48964ed8-7485-4895-abf6-54635af4df7b",
"context": {
"library": {
"name": "Analytics.NET",
"version": "2.0.3"
}
},

**Comment by f2prateek** [comment]
This is the Xamarin library. Analytics.NET (what you are using and reporting about)  is a different library https://github.com/segmentio/Analytics.Net.

We don't record the IP address for .Net events because it can be used from a server environment and would end up recording your servers IP address and that's not what most people want.

You can tell our servers to collect the IP for server side libraries if they're being used in a client environment by sending `context.direct` as true.

```
Analytics.Client.Page("019mr8mf4r", "Login", new Properties() {
    { "path", "/login" },
    { "title", "Initech Login" }
}, new Options()
    .SetContext (new Context () {
        { "direct", true },
});
```

Or send the IP manually https://segment.com/docs/sources/server/net/#context .

For future reference - you can send support questions to https://segment.com/contact.
